services:
  mpi_root:
    image: my-population-infection
    deploy:
      replicas: 1
    environment:
      - IS_ROOT=1
    ports: 
      - "22"
    networks:
      net:
        aliases:
          - mpi-root
    volumes:
      - type: bind
        source: ./results
        target: /home/mpirun/results
    command: \
      -N 10000 \
      -I 100 \
      -W 2000 \
      -L 3000 \
      -w 1000 \
      -l 1000 \
      -v 1.4 \
      -d 2 \
      --t-infection=60 \
      --t-recovery=3600 \
      --t-immunity=14400 \
      --sim-step=60 \
      --sim-length=14 \
      --log-level INFO

  mpi_worker:
    image: my-population-infection
    depends_on:
      - mpi_root
    deploy:
      replicas: 2
    networks:
      net:
        aliases:
          - mpi-worker
    volumes:
      - type: bind
        source: ./results
        target: /home/mpirun/results

networks:
  net:
    driver: bridge