services:
  mpi_root:
    image: my-population-infection
    deploy:
      replicas: 1
    environment:
      - IS_ROOT=1
    ports: 
      - "22"
    links: 
      - mpi_worker
    networks:
      net:
        aliases:
          - mpi-root
    volumes:
      - type: bind
        source: ./results
        target: /home/mpirun/results
    command: \
      -N 10000 \
      -I 100 \
      -W 10000 \
      -L 3000 \
      -w 5000 \
      -l 1000 \
      -v 7 \
      -d 5 \
      --t-infection=600 \
      --t-recovery=3600 \
      --t-immunity=10800 \
      --sim-step=1 \
      --sim-length=2

  mpi_worker:
    image: my-population-infection
    deploy:
      replicas: 2
    networks:
      net:
        aliases:
          - mpi-worker
    volumes:
      - type: bind
        source: ./results
        target: /home/mpirun/results

networks:
  net:
    driver: bridge